#' Detect the position of axis in binary image
#'
#' This function return the result of the position of y-axis and x-axis separately in a given binary image
#'
#' @param bi_matrix a two-dimension binary matrix generated by a binary image
#' @returns y_position the column index of the y-axis position
#' @returns x_position the row index of the x-axis position

detect_label = function(bi_matrix){
  y_range = dim(bi_matrix)[2]
  x_range = dim(bi_matrix)[1]
  y_position = 0
  x_position = 0
  for(i in seq(y_range)){
    if(axis_distance(bi_matrix[,i])>(0.6*y_range)){
      y_position = i
      break
    }
  }
  for(i in seq(x_range,1,-1)){
    if(axis_distance(bi_matrix[i,])>(0.5*x_range)){
      x_position = i
      break
    }
  }
  return(c(y_position,x_position))
}
