#' Get the position of extreme value on Axis
#'
#' This function returns the position of extreme value on Axis
#'
#' @param binary_matrix a two-dimension binary matrix generated by a binary image
#' @returns ymax_position the row index of the maximum y axis value on binary pixel image
#' @returns ymin_position the row index of the minimum y axis value on binary pixel image
#' @returns xmax_position the column index of the maximum x axis value on binary pixel image
#' @returns xmin_position the column index of the minimum x axis value on binary pixel image

get_label_position = function(binary_matrix){
  label_position = detect_label(binary_matrix)
  ymax_position = 1 # the width of image
  ymin_position = dim(binary_matrix)[1]
  xmin_position = 1 # the height of image
  xmax_position = dim(binary_matrix)[2]
  xaxis = binary_matrix[label_position[2],]
  yaxis = binary_matrix[,label_position[1]]
  while(xaxis[xmin_position]==1){xmin_position = xmin_position + 1 }
  while(xaxis[xmax_position]==1){xmax_position = xmax_position - 1 }
  while(yaxis[ymin_position]==1){ymin_position = ymin_position - 1 }
  while(yaxis[ymax_position]==1){ymax_position = ymax_position + 1 }
  return(c(ymax_position,ymin_position,xmin_position,xmax_position))
}




