#' Generate a binary matrix from a multi-channel pixel matrix.
#'
#' This function generate a binary_matrix from pixel_matrix with multiple channels like RGB or RGBA.
#'
#' @param pixel_matrix a three-dimension  matrix generated by a multiple channels image
#' @param threshold a number between 0 and 1. For pixel with value greater that threshold will be TRUE in return
#' @returns binary_matrix a binary matrix with the same dimension as the input matrix
get_binary_matrix = function(pixel_matrix, threshold = 0.8){
  single_channel = to_one_channel(pixel_matrix)
  binary_matrix = single_channel>threshold
  return(binary_matrix)
}
