#' Detect the value of a scatter plot
#'
#' This function returns the value of detected data set based on a standard scatter plot generated by ggplot::geom_point function.
#'
#' @param scatter_file the address of the scatter plot file.
#' @param ymax the maximum y value showing on the plot
#' @param ymin the minimum y value showing on the plot
#' @param xmin the maximum x value showing on the plot
#' @param xmax the minimum x value showing on the plot
#' @returns a two-column matrix with the predicted value of the data points.

scatter2data = function(scatter_file,ymax,ymin,xmax,xmin){
  origin_image = png::readPNG(scatter_file)
  bi_matrix = get_binary_matrix(origin_image)
  return(position2value(get_point_position(bi_matrix),get_label_position(bi_matrix),
                 ymax,ymin,xmax,xmin))
}
