#' select one channel from a multiple channel matrix
#'
#' This function returns the value of detected data set based on the position and axis extreme value information
#'
#' @param pixel_matrix a three-dimension matrix generated by a multiple channels image
#' @returns a two-dimension matrix
to_one_channel = function(pixel_matrix){
  return(pixel_matrix[,,1])
}
